Vagrant.configure("2") do |config|

	config.vm.define "pxeserver" do |server|
	
		server.vm.box = 'bento/ubuntu-22.04'
		server.vm.host_name = 'pxeserver' 
		
		server.vm.network "forwarded_port", guest: 80, host: 8080
		server.vm.network "forwarded_port", # дополнительный проброс порта для доступа к ВМ из WSL
			auto_correct: true,
			guest: 22,
			host: 2230, # Порт для подключения по ssh
			host_ip: "192.168.1.8", # Ip-адрес Windows-хоста
			id: "ssh-for-wsl"	
		server.vm.network :private_network, ip: "10.0.0.20", virtualbox__intnet: 'pxenet'
		
		server.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
		
	end
		
		config.vm.define "pxeclient" do |pxeclient|
		
		pxeclient.vm.box = 'bento/ubuntu-22.04'
		pxeclient.vm.host_name = 'pxeclient'
		
		pxeclient.vm.network :private_network, ip: "10.0.0.21"
		
		pxeclient.vm.provider :virtualbox do |vb|
			vb.memory = "4096"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize [
			'modifyvm', :id,
			'--nic1', 'intnet',
			'--intnet1', 'pxenet',
			'--boot1', 'net',
			]
		end

	end
	
end
