Vagrant.configure("2") do |config|
    config.vm.box = "centos/stream8"

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 1
    end

    boxes = [
      { :name => "ipa.otus.lan",
        :ip => "192.168.57.10",
        :wsl => 2216,
      },
      { :name => "client1.otus.lan",
        :ip => "192.168.57.11",
        :wsl => 2217,
      },
      { :name => "client2.otus.lan",
        :ip => "192.168.57.12",
        :wsl => 2218,
      }
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network "private_network", ip: opts[:ip]
        config.vm.network "forwarded_port", auto_correct: true, guest: 22, host: opts[:wsl], host_ip: "192.168.1.8", id: "ssh-for-wsl"
      end
    end
  end