# web:
all:
  vars:
    host_ip: 192.168.1.8
    dir_wsl: /home/sof/otus_labs/backup/
    dir_vagrant: /mnt/d/VBox_Projects/backup/

    vm_name_s: bcp_srv
    vm_port_s: 2227

    vm_name_c: bcp_clnt
    vm_port_c: 2228

    dir_borg: /mnt/bcp
    user_borg: borg




localhost:
    hosts:
        wsl:
            ansible_host: 127.0.0.1
            ansible_connection: local
vbox_vm:
    hosts:
        bcp_srv:
            ansible_host: "{{ host_ip }}"
            ansible_port: "{{ vm_port_s }}"
            ansible_private_key_file: "{{ 'certs/' + vm_name_s + '/private_key' }}"
        bcp_clnt:
            ansible_host: "{{ host_ip }}"
            ansible_port: "{{ vm_port_c }}"
            ansible_private_key_file: "{{ 'certs/' + vm_name_c + '/private_key' }}"
            repo: client1
            passphrase: borg
