localhost:
    hosts:
        wsl:
            ansible_host: 127.0.0.1
            ansible_connection: local
vm:
    hosts:
        ns01:
            ansible_host: 192.168.1.5
            ansible_port: 2223
            ansible_private_key_file: certs/ns01/private_key
            
        client:
            ansible_host: 192.168.1.5
            ansible_port: 2224
            ansible_private_key_file: certs/client/private_key