# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    ns01.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2219, host_ip: "192.168.1.8", id: "ssh-for-wsl"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "dns"
    ns02.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2220, host_ip: "192.168.1.8", id: "ssh-for-wsl"
    ns02.vm.hostname = "ns02"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
    client.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2221, host_ip: "192.168.1.8", id: "ssh-for-wsl"
    client.vm.hostname = "client"
  end

  config.vm.define "client2" do |client2|
    client2.vm.network "private_network", ip: "192.168.50.16", virtualbox__intnet: "dns"
    client2.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2223, host_ip: "192.168.1.8", id: "ssh-for-wsl"
    client2.vm.hostname = "client2"
  end

end
