# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "generic/ubuntu2204",
		:vm_name => "inetRouter",
        # :public => {:ip => '10.10.10.1', :adapter => 1},
		:wsl =>	[{auto_correct: true, guest: 22, host: 2229, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:centralRouter => {
        :box_name => "generic/ubuntu2204",
		:vm_name => "centralRouter",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2230, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
				   
				   {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
				   {ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
                ]
  }, 
:centralServer => {
		:box_name => "generic/ubuntu2204",
		:vm_name => "centralServer",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2231, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
				   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
				   # {adapter: 3, auto_config: false, virtualbox__intnet: true},
				   # {adapter: 4, auto_config: false, virtualbox__intnet: true},
				]
  },
:office1Router => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "office1Router",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2232, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
					{ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
					{ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
					{ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-central"},
					{ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
					{ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"},
                ]
  },
:office1Server => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "office1Server",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2233, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
					{ip: '192.168.2.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
                ]
  },
:office2Router => {
		:box_name => "generic/ubuntu2204",
		:vm_name => "office2Router",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2234, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
					{ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
					{ip: '192.168.3.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
					{ip: '192.168.3.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
					{ip: '192.168.3.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net"},
				]
  },
:office2Server => {
		:box_name => "generic/ubuntu2204",
		:vm_name => "office2Server",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2235, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
					{ip: '192.168.3.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
				]
  }
}

Vagrant.configure("2") do |config|
	MACHINES.each do |boxname, boxconfig|
		config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxconfig[:vm_name]

			box.vm.provider "virtualbox" do |v|
				v.memory = 768
				v.cpus = 1
			end

			boxconfig[:net].each do |ipconf|
				box.vm.network "private_network", **ipconf
			end

			boxconfig[:wsl].each do |pconf|
				box.vm.network "forwarded_port", **pconf
			end

			# if boxconfig.key?(:public)
				# box.vm.network "public_network", **boxconfig[:public]
			# end

			box.vm.provision "shell", inline: <<-SHELL
					mkdir -p ~root/.ssh
					cp ~vagrant/.ssh/auth* ~root/.ssh
					SHELL
		end
	end
end