# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "alma/8"
	config.vm.box_check_update = false

	config.vm.define "bash" do |bash|
		bash.vm.hostname = "bash"
		bash.vm.provider "virtualbox" do |v|
			v.name = "bash" 	# имя в VB
			v.memory = "2048"
			v.cpus = "1"
			v.gui = false
		end
	
		bash.vm.network "forwarded_port", # дополнительный проброс порта для доступа к ВМ из WSL
			auto_correct: true,
			guest: 22,
			host: 2226, # Порт для подключения по ssh
			host_ip: "192.168.1.8", # Ip-адрес Windows-хоста
			id: "ssh-for-wsl"		

		bash.vm.provision "shell", inline: <<-SHELL
			sudo mkdir -p ~root/.ssh
			sudo cp ~vagrant/.ssh/auth* ~root/.ssh
			sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
		SHELL
	end
end