# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "alma/8",
        :ip_addr => '192.168.11.150',
        :wsl =>	'2250'
  },
  :slave => {
        :box_name => "alma/8",
        :ip_addr => '192.168.11.151',
        :wsl =>	'2251'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.network "forwarded_port", auto_correct: true, guest: 22, host: boxconfig[:wsl], host_ip: "192.168.1.8", id: "ssh-for-wsl"
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end

      end
  end
end
