MACHINES = {
	:"pam" => {
			:box_name => "ubuntu/jammy64",
			:cpus => 2,
			:memory => 1024,
			:ip => "192.168.57.10",
			:wslp => "2228", # Порт для подключения по ssh из WSL
			:hostip => "192.168.1.8", #  # Ip-адрес Windows-хоста.
	}
}

Vagrant.configure("2") do |config|
	MACHINES.each do |boxname, boxconfig|
		config.vm.synced_folder ".", "/vagrant", disabled: true
		config.vm.network "private_network", ip: boxconfig[:ip]
		config.vm.network "forwarded_port", auto_correct: true, guest: 22, host: boxconfig[:wslp], host_ip: boxconfig[:hostip], id: "ssh-for-wsl" # дополнительный проброс порта для доступа к ВМ из WSL
		config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.box_version = boxconfig[:box_version]
			box.vm.host_name = boxname.to_s

		box.vm.provider "virtualbox" do |v|
			v.memory = boxconfig[:memory]
			v.cpus = boxconfig[:cpus]
		end
		box.vm.provision "shell", inline: <<-SHELL
			sudo -i
			sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
			sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
			systemctl restart sshd.service
		SHELL
		end
	end
end