all:
  vars: 
    vm_name: bash           # имя ВМ в VB
    host_ip: 192.168.1.8    # Ip-адрес Windows-хоста
    vm_port: 2226           # Порт для подключения по ssh
    dir_vagrant: /mnt/d/VBox_Projects/bash/     # Директория wsl, где расположены файлы windows-хоста
    dir_wsl: /home/sof/otus_labs/bash/       # Директория wsl, где расположены файлы ansible
    email_address: example@mail.ru      # Адрес электронной почты для отправки писем с ВМ


localhost:
    hosts:
        wsl:
            ansible_host: 127.0.0.1
            ansible_connection: local
vbox_vm:
    hosts:
        lab_vm:
            ansible_host: "{{ host_ip }}"
            ansible_port: "{{ vm_port }}"
            ansible_private_key_file: "{{ 'certs/' + vm_name + '/private_key' }}"
            
            