# -*- mode: ruby -*-
# vim: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

disks = {

	:sata1 => {
		:dfile => './sata1.vdi',
		:size => 250, # Megabytes
		:port => 1
	},
	:sata2 => {
		:dfile => './sata2.vdi',
		:size => 250, # Megabytes
		:port => 2
	},
	:sata3 => {
		:dfile => './sata3.vdi',
		:size => 250, # Megabytes
		:port => 3
	},
	:sata4 => {
		:dfile => './sata4.vdi',
		:size => 250, # Megabytes
		:port => 4
	},
	:sata5 => {
		:dfile => './sata5.vdi',
		:size => 250, # Megabytes
		:port => 5
	},

}

Vagrant.configure("2") do |config|


	config.vm.box = "centos/7"
	config.vm.box_check_update = false

	config.vm.define "raid" do |raid|

		raid.vm.hostname = "raid"	
		raid.vm.provider "virtualbox" do |v|
			v.name = "raid"
			v.memory = "2048"
			v.cpus = "1"
			v.gui = false
			v.customize ["modifyvm", :id, "--memory", "1024"]
			needsController = false
			disks.each do |dname, dconf|
				unless File.exist?(dconf[:dfile])
					v.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
					needsController =  true
				end
			end
			if needsController == true
				v.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
				disks.each do |dname, dconf|
					v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
				end
			end
			
		end
			
		raid.vm.provision "shell", inline: <<-SHELL
			sudo mkdir -p ~root/.ssh
			sudo cp ~vagrant/.ssh/auth* ~root/.ssh
			sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
		SHELL
	end
	
end