version: '2.2'
services:

    elastic:
        image: elasticsearch:8.9.2
        container_name: elastic
        restart: no
        networks:
            - elk
        ports:
            - "9200:9200"
        environment:
            - node.name=elastic
            # - cluster.name=es-docker-cluster
            # - discovery.seed_hosts=es-warm
            - cluster.initial_master_nodes=elastic
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.security.transport.ssl.verification_mode=none
            - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
        volumes:
            - elastic-data:/usr/share/elasticsearch/data
            - elastic-yml:/usr/share/elasticsearch/config
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536

    kibana:
        image: kibana:8.9.2
        container_name: kibana
        restart: no
        networks:
            - elk
        ports:
            - "5601:5601"
        volumes:
            - kibana-yml:/usr/share/kibana/config
        depends_on:
            - elastic


    logstash:
        image: logstash:8.9.2
        container_name: logstash
        restart: no
        networks:
            - elk
        ports:
            - "5046:5046"
            - "10514:10514"
        volumes:
            - logstash-conf:/usr/share/logstash/pipeline
            - logstash-yml:/usr/share/logstash/config
        depends_on:
            - elastic
            
    heartbeat:
        image: elastic/heartbeat:8.9.2
        container_name: heartbeat
        restart: no
        networks:
            - elk
        volumes:
            - heartbeat-yml:/usr/share/heartbeat
        depends_on:
            - kibana
            
    metricbeat:
        image: elastic/metricbeat:8.9.2
        container_name: metricbeat
        restart: no
        networks:
            - elk
        volumes:
            - metricbeat-yml:/usr/share/metricbeat
            - /proc:/hostfs/proc:ro
        depends_on:
            - kibana
            
    filebeat:
        image: elastic/filebeat:8.9.2
        container_name: filebeat
        restart: no
        networks:
            - elk
        volumes:
            - filebeat-yml:/usr/share/filebeat
            - /var/log:/var/log:ro
        depends_on:
            - kibana


volumes:
    elastic-data:
    elastic-yml:
    kibana-yml:
    logstash-conf:
    logstash-yml:
    heartbeat-yml:
    metricbeat-yml:
    filebeat-yml:

networks:
    elk:
        driver: bridge
 