version: '2.2'
services:

    loki:
        image: grafana/loki:2.9.1
        container_name: loki
        restart: no
        networks:
            - loki
        ports:
            - "3100:3100"
        volumes:
            - loki-conf:/etc/loki

    promtail:
        image: grafana/promtail:2.9.1
        container_name: promtail
        restart: no
        networks:
            - loki
        volumes:
            - promtail-conf:/etc/promtail
            - /var/log:/var/log:ro
            
    grafana:
        image: grafana/grafana:main
        container_name: grafana
        restart: no
        networks:
            - loki
        ports:
            - "3000:3000"  
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        entrypoint:
            - sh
            - -euc
            - |
              mkdir -p /etc/grafana/provisioning/datasources
              cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
              apiVersion: 1
              datasources:
              - name: Loki
                type: loki
                access: proxy 
                orgId: 1
                url: http://loki:3100
                basicAuth: false
                isDefault: true
                version: 1
                editable: false
              EOF
              /run.sh

volumes:
    loki-conf:
    promtail-conf:

networks:
    loki:
        driver: bridge