
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.box_check_update = false

	config.vm.define "kern_updt" do |kern_updt|
		kern_updt.vm.hostname = "kern-updt"				# hostname
		kern_updt.vm.provider "virtualbox" do |v|
			v.name = "kern_updt" 					# имя в VB
			v.memory = "2048"
			v.cpus = "1"
			v.gui = false
		end
	end
	
	config.vm.define "kern_new" do |kern_new|
		kern_new.vm.hostname = "kern-new"				# hostname
		kern_new.vm.provider "virtualbox" do |v|
			v.name = "kern_new2" 					# имя в VB
			v.memory = "2048"
			v.cpus = "1"
			v.gui = false
		end
	end
end