MACHINES = {
  :router1 => {
		:box_name => "ubuntu/focal64",
		:vm_name => "router1",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2210, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
                   {ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
                   {ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
                   {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net1"},
                ]
  },

  :router2 => {
		:box_name => "ubuntu/focal64",
		:vm_name => "router2",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2211, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
                   {ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
                   {ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
                   {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net2"},
                ]
  },

  :router3 => {
		:box_name => "ubuntu/focal64",
		:vm_name => "router3",
		:wsl =>	[{auto_correct: true, guest: 22, host: 2212, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
		:net => [
                   {ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
                   {ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
                   {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net3"},
                ]
  }

}

Vagrant.configure("2") do |config|

	MACHINES.each do |boxname, boxconfig|

		config.vm.define boxname do |box|

			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxconfig[:vm_name]

			boxconfig[:wsl].each do |pconf|
				box.vm.network "forwarded_port", **pconf
			end

			boxconfig[:net].each do |ipconf|
			box.vm.network "private_network", **ipconf
			end

		end
	end
end
