Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-22.04"
	config.vm.provider "virtualbox" do |v|
		v.memory = 1512
		v.cpus = 2
	end
	
	boxes = [
		{ :name => "web",
		  :ip => "192.168.56.10",
		  :wslp => "2223",
		  :hostip => "192.168.1.8",
		},
		{ :name => "log",
		  :ip => "192.168.56.15",
		  :wslp => "2224",
		  :hostip => "192.168.1.8",
		}
	]
	
	boxes.each do |opts|
		config.vm.define opts[:name] do |config|
			config.vm.hostname = opts[:name]
			config.vm.network "private_network", ip: opts[:ip]
			config.vm.network "forwarded_port", auto_correct: true, guest: 22, host: opts[:wslp], host_ip: opts[:hostip], id: "ssh-for-wsl"
		end
	end
end