global:
  scrape_interval: 5s
  external_labels:
    site: prod

rule_files:
  - /etc/prometheus/alert.rules.yml
    
scrape_configs:

    - job_name: 'prometheus'
      basic_auth:
        username: 'user_for_Prometheus'
        password: 'pass_for_Prometheus'
      static_configs:
        - targets: ['localhost:9090']
        
    - job_name: 'nginx'
      static_configs:
        - targets: ['exporter-nginx-wp:9113']
        
    - job_name: 'php-fpm'
      static_configs:
        - targets: ['exporter-fpm:9114']
        
    - job_name: 'windows'
      static_configs:
        - targets: ['host.docker.internal:9182']
        
    - job_name: 'cadvisor'
      static_configs:
        - targets: ['exporter-cadvisor:8080']
        
    - job_name: 'node'
      static_configs:
        - targets: ['exporter-node:9100']
        
    - job_name: 'mysql'
      static_configs:
        - targets: ['exporter-db-wp:9104']
        
    - job_name: 'container'
      static_configs:
        - targets: ['exporter-container:9104']
                  
    - job_name: blackbox-http
      honor_timestamps: true
      params:
        module:
          - http_2xx
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /probe
      scheme: http
      follow_redirects: true
      relabel_configs:
        - source_labels: [__address__]
          separator: ;
          regex: (.*)
          target_label: __param_target
          replacement: $1
          action: replace
        - source_labels: [__param_target]
          separator: ;
          regex: (.*)
          target_label: instance
          replacement: $1
          action: replace
        - separator: ;
          regex: (.*)
          target_label: __address__
          replacement: exporter-blackbox:9115
          action: replace
      static_configs:
        - targets:
            - http://host.docker.internal:8080
            - https://otus.ru
            
    - job_name: 'grafana'
      static_configs:
        - targets: ['graf:3000']

    - job_name: 'alertmanager'
      static_configs:
        - targets: ['alertmanager:9093']
        
    - job_name: 'victoria'
      static_configs:
        - targets: ['victoria:8428']
        
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
            
remote_write:
      - url: http://victoria:8428/api/v1/write