# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "alma/9"
	config.vm.box_check_update = false

	config.vm.define "rpm" do |rpm|

		rpm.vm.hostname = "rpm"				# hostname
		rpm.vm.provider "virtualbox" do |v|
			v.name = "rpm" 					# имя в VB
			v.memory = "2048"
			v.cpus = "2"
			v.gui = false
		end
	
	end
	
end