# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"

	config.vm.define "ns01" do |ns01|
		ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
		ns01.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2223, host_ip: "192.168.1.5", id: "ssh-for-wsl"
		ns01.vm.hostname = "ns01"
		ns01.vm.provider "virtualbox" do |v|
			v.memory = 256
			v.name = "selinux_ns01" 	# имя в VB
		end
		ns01.vm.provision "shell", inline: <<-SHELL
			sudo mkdir -p ~root/.ssh
			sudo cp ~vagrant/.ssh/auth* ~root/.ssh
			sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
		SHELL
	end

	config.vm.define "client" do |client|
		client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
		client.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2224, host_ip: "192.168.1.5", id: "ssh-for-wsl"
		client.vm.hostname = "client"
		client.vm.provider "virtualbox" do |v|
			v.memory = 256
			v.name = "selinux_client" 	# имя в VB
		end
		client.vm.provision "shell", inline: <<-SHELL
			sudo mkdir -p ~root/.ssh
			sudo cp ~vagrant/.ssh/auth* ~root/.ssh
			sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
		SHELL
	end
end
