# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/stream8",
        :vm_name => "inetRouter",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2240, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/stream8",
        :vm_name => "centralRouter",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2241, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                ]
  },

  :office1Router => {
        :box_name => "centos/stream8",
        :vm_name => "office1Router",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2242, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
                   {adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
                   {adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
                   {adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
                ]
  },

  :testClient1 => {
        :box_name => "centos/stream8",
        :vm_name => "testClient1",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2243, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                ]
  },

  :testServer1 => {
        :box_name => "centos/stream8",
        :vm_name => "testServer1",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2244, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
            ]
  },

  :testClient2 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "testClient2",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2245, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                ]
  },

  :testServer2 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "testServer2",
        :wsl =>	[{auto_correct: true, guest: 22, host: 2246, host_ip: "192.168.1.8", id: "ssh-for-wsl"}],
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end

      boxconfig[:wsl].each do |pconf|
				box.vm.network "forwarded_port", **pconf
			end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", **ipconf
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end
end
