Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/16"

	config.vm.define "nfss" do |nfss|
		nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "nfsnet"
		nfss.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2224, host_ip: "192.168.1.8", id: "ssh-for-wsl"
		nfss.vm.hostname = "nfss"
		nfss.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
			v.name = "nfss" 	# имя в VB
		end
		nfss.vm.provision "shell", inline: <<-SHELL
			sudo -i
			apt install nfs-kernel-server
			mkdir -p /srv/share/upload
			chown -R nobody:nogroup /srv/share
			chmod 0777 /srv/share/upload
			echo "/srv/share 192.168.50.11/32(rw,sync,root_squash)" >> /etc/exports
			exportfs -r
			touch /srv/share/upload/server_file
			reboot
		SHELL
	end

	config.vm.define "nfsc" do |nfsc|
		nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "nfsnet"
		nfsc.vm.network "forwarded_port", auto_correct: true, guest: 22, host: 2225, host_ip: "192.168.1.8", id: "ssh-for-wsl"
		nfsc.vm.hostname = "nfsc"
		nfsc.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
			v.name = "nfsc" 	# имя в VB
		end
		nfsc.vm.provision "shell", inline: <<-SHELL
			sudo -i
			apt install nfs-common
			echo "192.168.50.10:/srv/share/ /mnt nfs vers=3,proto=udp,noauto,x-systemd.automount 0 0" >> /etc/fstab
			systemctl daemon-reload
			systemctl restart remote-fs.target
			mount
			touch /mnt/upload/client_file
			reboot
		SHELL
	end
end