# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "centos/7-2004.01"
	config.vm.box_check_update = false

	config.vm.define "selinux" do |selinux|

		selinux.vm.hostname = "selinux"				# hostname
		selinux.vm.network "forwarded_port", guest: 4881, host: 4881
		selinux.vm.provider "virtualbox" do |v|
			v.name = "selinux" 					# имя в VB
			v.memory = "2048"
			v.cpus = "2"
			v.gui = false
			v.customize ["modifyvm", :id, "--memory", "1024"]
			needsController = false
		end
		
		selinux.vm.provision "shell", inline: <<-SHELL
			#install epel-release
			yum install -y epel-release
			#install nginx
			yum install -y nginx
			#change nginx port
			sed -ie 's/:80/:4881/g' /etc/nginx/nginx.conf
			sed -i 's/listen       80;/listen       4881;/' /etc/nginx/nginx.conf
			systemctl start nginx
			yum install -y policycoreutils-python
		SHELL
	end
end